### ISSUE TITLE
#Request For Add Genres to movies and tv and Fix (Maybe?) Year in inline mode

### ISSUE THREAD

**Issue by norm-git** [LBreda/moviedbbot#5]
I love the bot but here are my suggestions, thanks 
For To know what kind of genre is a certain movie or tv series / show. Like Action,  Science_Fiction and others.

Second is when looking for mode inline some movie or series that shows the year because now the bot does not. this way it would facilitate the search we want that we usually go by year or poster.
I attach a screenshot for a better understanding.
![IMG_20210718_155730_466](https://user-images.githubusercontent.com/63025079/126081907-ae027764-0d4f-4759-be3f-79ae00778c22.jpg)

**Comment by LBreda** [comment]
FIrst suggestion: ffa8e606399dfab37bddf8f6e1b2777dcdbb2cdc
Second suggestion: 50ca534b30981c07d44802a832472ff7720b8345

Thank you very much for your contribution!
